### ISSUE TITLE
Implement incomes

### ISSUE THREAD

**Issue by ivictbor** [devforth/trello-price-reports-collector-bot#2]
- If incomes present (items with + at the beginning) show them in a separate table
Show next result values (in spreadsheet and in bot response)

- incomes
- expenses
- profit
- loss

**Comment by yaboyaka** [comment]
![Screenshot from 2019-07-10 19-58-27](https://user-images.githubusercontent.com/48844430/60988821-27612d00-a34d-11e9-9706-d39fb5c32e9f.png)
